- name: '🚧 blocked'
  color: 'D93F0B'
  description: 'This issue is blocked by something else'
- name: '🏗️ build'
  color: 'FEF2C0'
  description: 'Changes that affect the build system or external dependencies.'
- name: '🔧 chore'
  color: '420663'
  description: 'Regular code maintenance.'
- name: '📝 content'
  color: 'E99695'
  description: 'Issues related to creating or updating content.'
- name: '❌ decided against'
  color: 'B60205'
  description: 'Stuff that we reviewed and decided not to do'
- name: '🔗 dependencies'
  color: 'cfd3d7'
  description: 'Pull requests that update a dependency file.'
- name: '📚 docs'
  color: 'E99695'
  description: 'For issues related to the docs site.'
- name: '📖 documentation'
  color: 'F9D0C4'
  description: 'Improvements or additions to documentation.'
- name: '🔍 dupe'
  color: 'FEF2C0'
  description: 'This issue or pull request already exists.'
- name: '✨ feat'
  color: 'C2E0C6'
  description: 'New feature or request.'
- name: '🔨 fix'
  color: 'D93F0B'
  description: "Something isn't working."
- name: '🙋 help'
  color: 'BFDADC'
  description: 'Extra attention is needed.'
- name: '💡 idea'
  color: 'C5DEF5'
  description: 'A possible idea or for future reference.'
- name: '⚡ perf'
  color: 'C5DEF5'
  description: 'A code change that improves performance.'
- name: '📝 planning'
  color: '46FD25'
  description: 'For research, scoping, and planning tasks'
- name: '🔧 project issue'
  color: 'D93F0B'
  description: 'Issues related to project management or organization.'
- name: '🔧 refactor'
  color: 'D4C5F9'
  description: 'A code change that neither fixes a bug nor adds a feature.'
- name: '🔖 reference'
  color: '5319E7'
  description: 'Something to review or consider in the future.'
- name: '↩️ revert'
  color: 'B60205'
  description: 'Reverts a previous commit.'
- name: '🎨 style'
  color: 'D9FDB3'
  description: 'Changes that do not affect the meaning of the code.'
- name: '🧪 test'
  color: '068E45'
  description: 'Adding missing or correcting existing tests.'
- name: '❌ wontfix'
  color: 'ffffff'
  description: 'This will not be worked on'
