/** @type {import('prettier').Config} */
module.exports = {
  bracketSpacing: true,
  endOfLine: 'lf',
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  bracketSpacing: true,
  arrowParens: 'always',
  printWidth: 80,
  tailwindFunctions: ['cn', 'clsx', 'tw'],
  tailwindConfig: './tailwind.config.js',
  importOrder: [
    '<BUILT_IN_MODULES>',
    '^(react/(.*)$)|^(react$)',
    '^(next/(.*)$)|^(next$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^types$',
    '^env$',
    '^public/fonts$',
    '',
    '^:/env(.*)$',
    '^:/types/(.*)$',
    '',
    '^#/config/(.*)$',
    '',
    '^#/lib/(.*)$',
    '^#/lib/hooks/(.*)$',
    '',
    '^#/components/(.*)$',
    '^#/styles/(.*)$',
    '',
    '^#/(.*)$',
    '',
    '^[./]',
  ],
  importOrderTypeScriptVersion: '5.0.0',
  plugins: [
    '@ianvs/prettier-plugin-sort-imports',
    'prettier-plugin-tailwindcss',
  ],
};
