name: 🛠 Project Issue
description: Got a project issue? Let's sort it out.
title: 'issue: '
labels: ['🔧 project issue']
assignees: ['srizvi']
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: What's this about?
      description: Is this a new feature or maintenance work?
      options:
        - New feature
        - Maintenance
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's up now?
      description: Give us the lowdown. What's the current situation?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's the goal?
      description: What should it be? Let's visualize the win.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's the plan?
      description: How you going to make it happen? Share your plan here.
    validations:
      required: true
